### ISSUE TITLE
PvaClientMonitor::releaseEvent did not call poll

### ISSUE THREAD

**Issue by mdavidsaver** [epics-base/pvaPy#18]
Same test environment as #17 terminated with unhandled exception.  Not sure if this issue is with pvaPy or pvaClientCPP.  No dis/reconnect involved here.

```
1.0 1.0
terminate called after throwing an instance of 'std::runtime_error'
  what():  PvaClientMonitor::releaseEvent did not call poll
Aborted
```

**Comment by sveseli** [comment]
New monitor code has structure similar to the one without pvaClientCPP library, with monitor requester. The monitor requester will never call releaseEvent() unless poll() succeeds. What could happen is that releaseEvent() gets called after monitor is stopped, but this exception is caught and should not cause problems for the rest of the client code.
