### ISSUE TITLE
Type IDs cannot be set when creating structures or structure arrays

### ISSUE THREAD

**Issue by dhickin** [epics-base/pvaPy#25]
The current Python API doesn't seem to allow creating a structure with anything other than a default type ID.

If this is the the case pvaPy will not be usable in a real system, since code written in C++/Java is setting the type IDs when creating structures and expecting to them to be set when receiving them.

PvObject does have constructors which take a type ID, so these just need to be exposed in pvaccess.PvObject.cpp

``` C++
    .def(init<boost::python::dict,const std::string &>(args("structureDict","typeId")))
```

Which allows structures with type IDs to be created in Python

``` Python
print PvObject({'value' : DOUBLE}, 'epics:nt/NTScalar:1.0')
```

However this only allows for creation of top-level IDs. It doesn't allow for setting the type ID of lower-level structures. It looks difficult to create a general structure, including type IDs, using a single dictionary. Since dictionaries, tuples and lists all have special meanings (as structures, unions and arrays) it's not easy to supply an additional string.

It would possible to do it this way

``` Python
struc3 = PvObject({ 'leaf'   : DOUBLE }, 'type3')
struc2 = PvObject({ 'struc3' : struc3 }, 'type2')
struc1 = PvObject({ 'struc2' : struc2 }, 'type1')
```

However this requires a change to PyPvDataUtility as the latter loses the type IDs when you use a PvObject to create a subfield. I have this solution for this which generates

<pre>
type1 
    type2 struc2
        type3 struc3
            double leaf 0
</pre>

as required. I'll raise the pull request.

Similar comments also apply to structure arrays. I have a similar fix to that for structures, which I'll include in the pull request.

**Comment by sveseli** [comment]
Thanks for the fixes.
