### ISSUE TITLE
Possible ref. loops

### ISSUE THREAD

**Issue by mdavidsaver** [epics-base/pvaPy#33]
From the discussion in https://github.com/epics-base/pvAccessCPP/pull/60 I've looked for code using PVA.

@msekoranja states that a Requester should never hold a strong reference (shared_ptr) to the associated Operation.  Doing so creates a reference loop which must be explicitly broken as the Operation holds a strong ref. to its Requester.  For example, in src/pvaccess/ChannelGetRequesterImpl.h ```ChannelGetRequesterImpl::channelGet```.  I haven't look any further than the header, so I don't know if this particular instance is causing a problem.  So FYI...

**Comment by sveseli** [comment]
This should not be a problem; in this particular case reference was unused, and has now been removed.
