### ISSUE TITLE
Please use a more appropriate installation directory for the generated shared library

### ISSUE THREAD

**Issue by ralphlange** [epics-base/pvaPy#4]
pvaPy generates a shared library called **pvaccess.so**

This is a bad choice of name, as pvAccess itself creates **libpvAccess.so**. Such ambiguous naming will be a source of confusion and mistakes.

Please chose a name that is more unique and comprehensive.

**Comment by mdavidsaver** [comment]
IMO the issue is namespace.  The pvaPy generated library is a python module, so it's name is part of the API (ie "import pvaccess").  However, it shouldn't be install in the regular lib/ directory.

**Comment by mdavidsaver** [comment]
FYI, for https://github.com/mdavidsaver/pyDevSup I install python stuff in "$(INSTALL_LOCATION)/python$(PY_VER)/$(T_A)".  For example "$(TOP)/python2.7/linux-x86/".  Then this directory needs to be added to $PYTHONPATH.

**Comment by sveseli** [comment]
Yes, this would be better installation directory. Configuration does 
result in user setup.(c)sh that can be sourced and PYTHONPATH would be 
setup correctly.

**Comment by sveseli** [comment]
Like Michael said, the reason why this is done is simply how python works.

**Comment by ralphlange** [comment]
Understood.
My original wording should have been: Installing **pvaccess.so** and **libpvAccess.so** _in the same place_ will be a source of confusion and mistakes.
Changing the installation directory is a good solution. Changing the issue title accordingly.
