### ISSUE TITLE
deprecated methods of pvaClientCPP

### ISSUE THREAD

**Issue by mrkraimer** [epics-base/pvaPy#40]
The following deprecated methods of pvaClientCPP are called:
static PvaClientPtr create() EPICS_DEPRECATED
and
static PvaClientMonitorPtr create(
        PvaClientPtr const &pvaClient,
        std::string const & channelName,
        std::string const & providerName,
        std::string const & request,
        PvaClientChannelStateChangeRequesterPtr const & stateChangeRequester
            = PvaClientChannelStateChangeRequesterPtr(),
        PvaClientMonitorRequesterPtr const & monitorRequester 
            = PvaClientMonitorRequesterPtr() ) EPICS_DEPRECATED;

https://github.com/mrkraimer/pvaPy
has changes so that these two methods are no longer called.

I want to do some more testing before a pull request is created.
For now anyone who is interested can clone the mrkraimer repository.

**Comment by sveseli** [comment]
Marty's changes have been incorporated into the master branch.
