### ISSUE TITLE
needs a version string

### ISSUE THREAD

**Issue by prjemian** [epics-base/pvaPy#43]
Such as:

    import pvaccess
    print(pvaccess.__version__)

One useful tool: https://github.com/warner/python-versioneer

**Comment by sveseli** [comment]
This will be resolved as of 1.1.0. Current conda packages and code on master branch already have version string.

bluegill2> python
Python 3.6.3 |Anaconda, Inc.| (default, Nov 20 2017, 20:41:42) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pvaccess
>>> pvaccess.__version__
'1.1.0rc6'
>>>
