### ISSUE TITLE
Setting Timeout for RpcClient

### ISSUE THREAD

**Issue by sasaki77** [epics-base/pvaPy#44]
I would like to set timeout for RpcClient, but there seems be no way to set it. The timeout is set as DefaultTimeout and its value is 1. It is convenient if there are getTimeout and setTimeout like Channel class. Do you have any plan for RpcClient timeout?

**Comment by sveseli** [comment]
Could you please try the latest code (anything after commit 3d5a0d51) from the master branch, and see if invoking RpcClient with the specified timeout works for you?

**Comment by sasaki77** [comment]
Thank you for implementing. setTimeout and invoking with timeout argument are  working as expected.
