### ISSUE TITLE
Question about setting timeStamp

### ISSUE THREAD

**Issue by douglasbeniz** [epics-base/pvaPy#47]
Hello guys! At first, nice work, thank you!

We're trying to update timeStamp of a PV at the moment it is being assigned if I can say that way. The way we're doing seems to be not supported by the library, and we wonder if it would have a good reason to forbid such timeStamp assignment, probably yes... but then, it has a way to do it? We just need to have that timeStamp available at the PV for syncing with another service...
```
import pvaccess
timeStamp = pvaccess.PvTimeStamp(12345678, 12)
timeStamp
<pvaccess.pvaccess.PvTimeStamp at 0x7f8e6b536050>
print(timeStamp)
time_t 
    long secondsPastEpoch 12345678
    int userTag -1
    int nanoseconds 12
pvTest = pvaccess.PvObject({'value':pvaccess.STRING, 'timeStamp':pvaccess.PvTimeStamp}, {'value':'pvTest001', 'timeStamp':timeStamp})
InvalidArgument: Unrecognized structure type for field name timeStamp
```

Thank you for any guidance!
/ Douglas B Beniz

**Comment by sveseli** [comment]
Could you please try something like this and let me know if it works:

```
>>> from pvaccess import *
>>> ts = PvTimeStamp(12345678, 12)
>>> pv = PvObject({'value':STRING, 'timeStamp':ts}, {'value':'pvTest001', 'timeStamp':ts.toDict()}) 
>>> print(pv)
structure 
    string value pvTest001
    time_t timeStamp
        long secondsPastEpoch 12345678
        int nanoseconds 12
        int userTag -1
```

**Comment by douglasbeniz** [comment]
That works perfectly! Thank you very much @sveseli!

Cheers!
