### ISSUE TITLE
Question about alarms

### ISSUE THREAD

**Issue by douglasbeniz** [epics-base/pvaPy#48]
Hello again...

We're now trying to set an alarm to a PV.

Firstly, being honest, I still have a question if pvaPy should do this (in fact I'm helping someone else, so, I'm still understanding the requirements and why they decided to use pvaPy).

Then, what is desired (and my questions are: first, is possible to do it using pvaPy, second, how to do it):
* set alarms
* set limits (lolo, lo, hi, hihi)
* if the value reaches limits, then alarms being set automatically.

Go to what we (they) did (and the alarms were not set automatically, as I expected because we didn't programme anything to set the alarms considering the value):

```
from pvaccess import *

# assigning some objects
# ----------------------------------------------
# PvTimeStamp(<long secondsPastEpoch>,
#             <int nanoseconds>,
#             <int userTag=-1>)
# ----------------------------------------------
ts      = PvTimeStamp(12345678, 12)
# ----------------------------------------------
# PvAlarm(<int severity>,
#         <int status>,
#         <string message>)
# ----------------------------------------------
alarm   = PvAlarm(13,-1,'testing an error!')

# creating a PV object
pv = PvObject(  {'value':           FLOAT,
                    'timeStamp':    ts,
                    'alarm':        alarm,
                    'descriptor':   STRING,
                    'lo':           FLOAT,
                    'lolo':         FLOAT,
                    'hi':           FLOAT,
                    'hihi':         FLOAT },
                {'value':           250.67
                    'timeStamp':    ts.toDict(),
                    'alarm':        alarm.toDict(),
                    'descriptor':   'A first test PV name 001',
                    'lo':           -321.15,
                    'lolo':         -321.75,
                    'hi':           32.65,
                    'hihi':         33.00} )

print(pv)

# ----------------------------------------------
# output
# ----------------------------------------------
douglasbeniz@douglasbeniz-thinkpad:~/Documents$ python pvaPy_example.py 
structure 
    string descriptor A first test PV name 001
    float hi 32.65
    float lo -321.15
    time_t timeStamp
        long secondsPastEpoch 12345678
        int userTag -1
        int nanoseconds 12
    alarm_t alarm
        int status -1
        string message testing an error!
        int severity 13
    float hihi 33
    float lolo -321.75
    float value 250.67
```

**Comment by sveseli** [comment]
PvaPy can process record on write using on write callback. Hence, if you wanted to do this using pvapy, you can (see https://epics.anl.gov/extensions/pvaPy/production/pvaccess.html#pvaserver). As far as I know, the underlying PV Database records are not doing any processing automatically at the moment.

**Comment by mrkraimer** [comment]
I will start adding support for control and valueAlarm in PVRecord.
There is a method PVRecord::process that already has support for updating the timeStamp.
I will let it also implement control and valueAlarm if those fields exist at top level of record.

**Comment by douglasbeniz** [comment]
> PvaPy can process record on write using on write callback. Hence, if you wanted to do this using pvapy, you can (see https://epics.anl.gov/extensions/pvaPy/production/pvaccess.html#pvaserver). As far as I know, the underlying PV Database records are not doing any processing automatically at the moment.

Hey, Sinisa, thank you for your answer! To be honest, I expected something like that, I mean, we need to implement the behaviour when a PV value reaches such limits. I think we can use PvaServer by now...

I was studying channel monitors that seem to be an option already available, too.

**Comment by douglasbeniz** [comment]
> I will start adding support for control and valueAlarm in PVRecord.
> There is a method PVRecord::process that already has support for updating the timeStamp.
> I will let it also implement control and valueAlarm if those fields exist at top level of record.

That would be awesome, Marty! Thank you. I'll follow the next updates, so...
