### ISSUE TITLE
std::bad_weak_ptr when removing records

### ISSUE THREAD

**Issue by jjaraalm** [epics-base/pvaPy#49]
I'm not sure if this a pvapy issue or upstream in EPICS, but removing a record with a connected channel throws an error and causes python to temrinate.

```python
s = pva.PvaServer('foo', pva.PvObject({'value': pva.INT}))
c = pva.Channel('foo')
c.get()
s.removeRecord('foo')
```

results in

``` 
terminate called after throwing an instance of 'std::bad_weak_ptr'
  what():  bad_weak_ptr
```

I'm using `pvapy=1.6.0` and `epics-base=7.0.2.2`.

**Comment by sveseli** [comment]
Marty's commit  248ce50 fixed this issue.
