### ISSUE TITLE
PvObject set

### ISSUE THREAD

**Issue by thomasms** [epics-base/pvaPy#60]
Hi, 

I've encountered an odd issue, but I am not sure if this is a feature or a bug, I am hoping you can clarify.

I notice that when using the `set` method on PvObject the order of key-value pairs in the dictionary passed to the method can affect subscribers. For example:

```python
pv1 = pvapy.PvObject(.....)

# these two are not the same
pv1.set({'a': 1, 'b': 2})
pv1.set({'b': 2, 'a': 1})
```

For a full reproducible example, please see the snippet below:
```python
#!/usr/bin/env python

import time
from datetime import datetime

import pvapy as pv

EPOCH = datetime.utcfromtimestamp(0)

def timestampnow():
    dt = datetime.now() - EPOCH
    seconds_since_epoch = int(dt.total_seconds())
    nanoseconds = int(dt.microseconds * 1e3)
    return pv.PvTimeStamp(seconds_since_epoch, nanoseconds)

# my PV
pv1 = pv.PvObject(
    {
        "value": pv.INT,
        "timeStamp": {
            "secondsPastEpoch": pv.LONG,
            "nanoseconds": pv.INT,
            "userTag": pv.INT,
        },
    },
    {
        "value": 0,
        "timeStamp": {
            "secondsPastEpoch": 0,
            "nanoseconds": 0,
            "userTag": 0,
        },
    },
)

# setup a server
server = pv.PvaServer("mypvtest", pv1)

# callback
def echo(x):
    print(
        "** CLIENT **",
        datetime.fromtimestamp(x["timeStamp"]["secondsPastEpoch"]).strftime(
            "%Y-%m-%d %H:%M:%S.%f"
        ),
        x["value"]
    )

# client - subscriber
channel = pv.Channel("mypvtest", pv.ProviderType.PVA)
channel.subscribe("mon", echo)
channel.startMonitor()

counter = 0
while True:
    x = counter
    ts = timestampnow()
    # replace this line with the other below it and notice the difference in output
    pv1.set({"timeStamp": ts, "value": x})
    #pv1.set({"value": x,"timeStamp": ts})
    print(
        "** SERVER **",
        datetime.fromtimestamp(ts["secondsPastEpoch"]).strftime("%Y-%m-%d %H:%M:%S.%f"),
        x
    )
    time.sleep(1)
    counter = counter + 1 if counter < 9 else 0
```

With timeStamp first we see this output:
```bash
** SERVER ** 2021-05-28 14:51:21.000000 0
** CLIENT ** 2021-05-28 14:51:21.000000 0
** SERVER ** 2021-05-28 14:51:22.000000 1
** CLIENT ** 2021-05-28 14:51:22.000000 0
** SERVER ** 2021-05-28 14:51:23.000000 2
** CLIENT ** 2021-05-28 14:51:23.000000 1
** SERVER ** 2021-05-28 14:51:24.000000 3
** CLIENT ** 2021-05-28 14:51:24.000000 2
** SERVER ** 2021-05-28 14:51:25.000000 4
** CLIENT ** 2021-05-28 14:51:25.000000 3
** SERVER ** 2021-05-28 14:51:26.000000 5
** CLIENT ** 2021-05-28 14:51:26.000000 4
** SERVER ** 2021-05-28 14:51:27.000000 6
** CLIENT ** 2021-05-28 14:51:27.000000 5
** SERVER ** 2021-05-28 14:51:28.000000 7
** CLIENT ** 2021-05-28 14:51:28.000000 6
** SERVER ** 2021-05-28 14:51:29.000000 8
** CLIENT ** 2021-05-28 14:51:29.000000 7
** SERVER ** 2021-05-28 14:51:30.000000 9
** CLIENT ** 2021-05-28 14:51:30.000000 8
** SERVER ** 2021-05-28 14:51:31.000000 0
** CLIENT ** 2021-05-28 14:51:31.000000 9
** SERVER ** 2021-05-28 14:51:32.000000 1
** CLIENT ** 2021-05-28 14:51:32.000000 0
** SERVER ** 2021-05-28 14:51:33.000000 2
** CLIENT ** 2021-05-28 14:51:33.000000 1
** SERVER ** 2021-05-28 14:51:34.000000 3
** CLIENT ** 2021-05-28 14:51:34.000000 2

```

whereas the other way around we see this output.
```bash
** SERVER ** 2021-05-28 14:52:59.000000 0
** CLIENT ** 2021-05-28 14:52:59.000000 0
** SERVER ** 2021-05-28 14:53:00.000000 1
** CLIENT ** 2021-05-28 14:52:59.000000 1
** SERVER ** 2021-05-28 14:53:01.000000 2
** CLIENT ** 2021-05-28 14:53:00.000000 2
** SERVER ** 2021-05-28 14:53:02.000000 3
** CLIENT ** 2021-05-28 14:53:01.000000 3
** SERVER ** 2021-05-28 14:53:03.000000 4
** CLIENT ** 2021-05-28 14:53:02.000000 4
** SERVER ** 2021-05-28 14:53:04.000000 5
** CLIENT ** 2021-05-28 14:53:03.000000 5
** SERVER ** 2021-05-28 14:53:05.000000 6
** CLIENT ** 2021-05-28 14:53:04.000000 6
** SERVER ** 2021-05-28 14:53:06.000000 7
** CLIENT ** 2021-05-28 14:53:05.000000 7
** SERVER ** 2021-05-28 14:53:07.000000 8
** CLIENT ** 2021-05-28 14:53:06.000000 8
** SERVER ** 2021-05-28 14:53:08.000000 9
** CLIENT ** 2021-05-28 14:53:07.000000 9
** SERVER ** 2021-05-28 14:53:09.000000 0
** CLIENT ** 2021-05-28 14:53:08.000000 0
** SERVER ** 2021-05-28 14:53:10.000000 1
** CLIENT ** 2021-05-28 14:53:09.000000 1
** SERVER ** 2021-05-28 14:53:11.000000 2
** CLIENT ** 2021-05-28 14:53:10.000000 2
** SERVER ** 2021-05-28 14:53:12.000000 3
** CLIENT ** 2021-05-28 14:53:11.000000 3

```

You can see in the first one the times are in sync but the values are not, similarly, in the other one the values are in sync but not the times. 

My question is, if this is a feature how can I set the both at the same time, so both timestamp and value are in sync with subscribers? If it is a bug, do you know of a workaround?

Thanks,
Tom

**Comment by thomasms** [comment]
I believe the culprit code causing this is from file PyPvDataUtility.cpp, which seems to iterate over the keys and do each put separately. Therefore, it seems this is not a bug but how does one go about changing two or more fields at the same time i.e. in one put?

```cpp
void pyDictToStructure(const bp::dict&amp; pyDict, pvd::PVStructurePtr&amp; pvStructurePtr){
    bp::list keys = pyDict.keys();
    for (int i = 0; i &lt; bp::len(keys); i++) {
        bp::object keyObject = keys[i];
        bp::extract&lt;std::string&gt; keyExtract(keyObject);
        std::string key;
        if (keyExtract.check()) {
            key = keyExtract();
        }
        else {
            throw InvalidDataType("Dictionary key must be a string");
        }
        bp::object pyObject = pyDict[keyObject];
        pyObjectToField(pyObject, key, pvStructurePtr);
    }
}

```

**Comment by sveseli** [comment]
Hi Tom,

Could you try the following  change:
<pre>
(daq) bluegill2> diff set.py set.py.orig 
37c37
< server = pv.PvaServer("mypvtest", pv1.copy())
---
> server = pv.PvaServer("mypvtest", pv1)
60d59
<     server.update('mypvtest', pv1)
(daq) bluegill2> 
</pre>

When I run the new code in my environment, I see this:
<pre>
daq) bluegill2> python set.py
2021-05-28T14:21:28.608 Using dynamically assigned TCP port 52692.
pvAccess Server v7.1.2
Active configuration (w/ defaults)
EPICS_PVAS_INTF_ADDR_LIST = 0.0.0.0:5075
EPICS_PVAS_BEACON_ADDR_LIST = 164.54.188.7 apsu-am310-1p0 ctlsdaqdev1.aps4.anl.gov ctlsdaqdev6 ctlsdaqdev7 ctlsdaqsrv1 ctlsdaqsrv2 s27tbt-eth0.aps4.anl.gov
EPICS_PVAS_AUTO_BEACON_ADDR_LIST = YES
EPICS_PVAS_BEACON_PERIOD = 15
EPICS_PVAS_BROADCAST_PORT = 5076
EPICS_PVAS_SERVER_PORT = 52692
EPICS_PVAS_PROVIDER_NAMES = local
** SERVER ** 2021-05-28 09:21:28.000000 0
** CLIENT ** 2021-05-28 09:21:28.000000 0
** SERVER ** 2021-05-28 09:21:29.000000 1
** CLIENT ** 2021-05-28 09:21:29.000000 1
** SERVER ** 2021-05-28 09:21:30.000000 2
** CLIENT ** 2021-05-28 09:21:30.000000 2
** SERVER ** 2021-05-28 09:21:31.000000 3
** CLIENT ** 2021-05-28 09:21:31.000000 3
** SERVER ** 2021-05-28 09:21:32.000000 4
** CLIENT ** 2021-05-28 09:21:32.000000 4
** SERVER ** 2021-05-28 09:21:33.000000 5
** CLIENT ** 2021-05-28 09:21:33.000000 5
** SERVER ** 2021-05-28 09:21:34.000000 6
** CLIENT ** 2021-05-28 09:21:34.000000 6
** SERVER ** 2021-05-28 09:21:35.000000 7
** CLIENT ** 2021-05-28 09:21:35.000000 7
** SERVER ** 2021-05-28 09:21:36.000000 8
** CLIENT ** 2021-05-28 09:21:36.000000 8
** SERVER ** 2021-05-28 09:21:37.000000 9
** CLIENT ** 2021-05-28 09:21:37.000000 9
</pre>

The update() method is guaranteed to be atomic.

**Comment by thomasms** [comment]
Great, that works indeed!
Thanks for the help. I'll close the issue.
