### ISSUE TITLE
Suppress pvInfo stdout

### ISSUE THREAD

**Issue by thomasms** [epics-base/pvaPy#62]
Hi,

Not sure if this is an issue, but I would like to know how to suppress the std out from the C++ pvAccess library which shows everytime you start up a PvaServer:

```
pvAccess Server v7.1.2
Active configuration (w/ defaults)
EPICS_PVAS_INTF_ADDR_LIST = 0.0.0.0:5075
EPICS_PVAS_BEACON_ADDR_LIST =
EPICS_PVAS_AUTO_BEACON_ADDR_LIST = YES
EPICS_PVAS_BEACON_PERIOD = 15
EPICS_PVAS_BROADCAST_PORT = 5076
EPICS_PVAS_SERVER_PORT = 5075
EPICS_PVAS_PROVIDER_NAMES = local
```

I can't find any option in the documentation, but maybe I've been looking in the wrong place.

Any help on this would be greatly appreciated.

**Comment by sveseli** [comment]
This will be addressed in the next release. Server info will only be printed if log level is set to debug or info levels (see commit 7e83935):

<pre>
$ PVAPY_LOG_LEVEL=255 python -c "from pvaccess import *; s = PvaServer()"
pvAccess Server v7.1.3
Active configuration (w/ defaults)
EPICS_PVAS_INTF_ADDR_LIST = 0.0.0.0:5075
EPICS_PVAS_BEACON_ADDR_LIST = 
EPICS_PVAS_AUTO_BEACON_ADDR_LIST = YES
EPICS_PVAS_BEACON_PERIOD = 15
EPICS_PVAS_BROADCAST_PORT = 5076
EPICS_PVAS_SERVER_PORT = 5075
EPICS_PVAS_PROVIDER_NAMES = local
2021/06/30 16:41:30.498 DEBUG PvaServer:  Started PVA Server callback thread CallbackThread
2021/06/30 16:41:30.502 DEBUG PvaServer:  Waiting on callback thread exit, timeout in 0.100000 seconds
2021/06/30 16:41:30.503 DEBUG PvaServer:  Exiting PVA Server callback thread CallbackThread


$ python -c "from pvaccess import *; s = PvaServer()"
$ 
</pre>
