### ISSUE TITLE
2 questions about usage

### ISSUE THREAD

**Issue by mattclarke** [epics-base/pvaPy#64]
Hi.

Sorry but I have some questions which I am struggling to find answers to.

1) I can subscribe to a PV and get its value change events, but I cannot seem to find a way to supply a callback for notification when the PV disconnects. Is there a way to do this that I am missing?

2) Is it possible to do a blocking/waiting put? E.g. something like: chan.put('MY:PV', 10, wait=True)

Thanks

**Comment by sveseli** [comment]
Hi,

You can always post a question to tech-talk and I will try to help. Alternatively, you can send me email directly. Posting issue here is also fine.  

Something like this should work for connection callbacks:

<pre>
$ python
Python 3.7.9 (default, Aug 31 2020, 12:42:55)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pvapy import *
>>> def connCallback(isConnected):
...     print('Connected: %s' % isConnected)
...
>>> c = Channel('xyz', PVA)
>>> c.setConnectionCallback(connCallback)
Connected: False
>>> pv = PvObject({'x':INT}, {'x':3})
>>> s = PvaServer('xyz', pv)
2020-12-22T15:19:56.791 Using dynamically assigned TCP port 42582.
pvAccess Server v7.1.1
Active configuration (w/ defaults)
EPICS_PVAS_INTF_ADDR_LIST = 0.0.0.0:5075
EPICS_PVAS_BEACON_ADDR_LIST = 164.54....
EPICS_PVAS_AUTO_BEACON_ADDR_LIST = YES
EPICS_PVAS_BEACON_PERIOD = 15
EPICS_PVAS_BROADCAST_PORT = 5076
EPICS_PVAS_SERVER_PORT = 42582
EPICS_PVAS_PROVIDER_NAMES = local
>>> Connected: True
</pre>

As far as blocking put, right now the call will throw a timeout exception if channel is not available, so one would have to catch it and try again until channel comes back up. Alternatively, one could use the connection callback to figure out when the PV is available, and then try put.

**Comment by mattclarke** [comment]
Perfect - thank you!
