### ISSUE TITLE
PvAlarm and PvTimeStamp do not work for put

### ISSUE THREAD

**Issue by mrkraimer** [epics-base/pvaPy#65]
The following is putTime.py:

    from pvapy import Channel, PvTimeStamp
    channel = Channel('PVRdouble')
    timestamp = PvTimeStamp(10, 100,1)
    print('start value=',channel.get('timeStamp'))
    channel.put(timestamp,'record[process=false]field(timeStamp)')
    val = channel.get('value,alarm,timeStamp')
    print('after put timeStamp value=',channel.get('timeStamp'))

It uses the database from exampleCPP

When the database is started and the following is issued

    python putTime.py

The following is the result

    start value= structure 
    time_t timeStamp
        long secondsPastEpoch 0
        int nanoseconds 0
        int userTag 0

    after put timeStamp value= structure 
    time_t timeStamp
        long secondsPastEpoch 0
        int nanoseconds 0
        int userTag 0

Maybe the problem is  that none of the PvAlarm and PyTimeStamp code has a get method?

**Comment by mrkraimer** [comment]
I have found that in

    void Channel::put(const PvObject& pvObject, const std::string& requestDescriptor) 
    {
        connect();
        try {
            epics::pvaClient::PvaClientPutPtr pvaPut = createPutPtr(requestDescriptor);
            epics::pvData::PVStructurePtr pvSend = pvaPut->getData()->getPVStructure();
            pvSend << pvObject;
            pvaPut->put();
        } 
            catch (std::runtime_error& ex) {
            throw PvaException(ex.what());
         }
    }

The statement 

    pvSend << pvObject;

Does NOT do anything.
Also, for PvAlarm and PyTimeStamp,  pvObject is a single field, but pvSend is a structure.

**Comment by mrkraimer** [comment]
I  created a pull request #66 that fixes the problem for pvDatabase records.

**Comment by sveseli** [comment]
Thanks for the fixes. I have slightly modified PR #66 after merge in order to make put() work with objects that have matching structures as before (see commit d0f5444).
