### ISSUE TITLE
Async functionality should propagate the errors/exceptions to the caller

### ISSUE THREAD

**Issue by MaticPogacnik** [epics-base/pvaPy#68]
Recently the `asyncGet` was added, which works as expected.
But the exceptions (e.g. Timeout) are just logged and not propagated to the user.

I see two possibilities how this could be added (there are probably more):
 - Add a separate callback, which is called on the error. 
 - Add extra arguments to the existing callback, which provide the status information.
 
@sveseli

**Comment by anjohnson** [comment]
Hi Matic, FYI Sinisa is now "out of the office" until mid-September, so you might not get a response until he gets back (although it wouldn't surprise me if he checks his email occasionally).

**Comment by echandler-anl** [comment]
FYI we found a separate issue related to async:  async get/put block if they can't connect to the PV.  Connection needs to happen on the async thread.

**Comment by sveseli** [comment]
@MaticPogacnik fixes have been incorporated into the code as of release 4.0.1.
