### ISSUE TITLE
compile for aarch64

### ISSUE THREAD

**Issue by lzhengchun** [epics-base/pvaPy#70]
I am trying to compile and install it on NVIDIA Jetson TX2 using the automated compiling solution. but got errors as follow. appreciate if someone can help to figure out a solution 

configure: Verifying boost python library
checking whether boost_python37 is the correct library... no
checking whether boost_python37 is the correct library... (cached) no
checking whether boost_python37 is the correct library... (cached) no
checking whether boost_python37 is the correct library... (cached) no
checking whether boost_python37 is the correct library... (cached) no
checking whether boost_python is the correct library... no
checking whether boost_python is the correct library... (cached) no
checking whether boost_python3 is the correct library... no
configure: error: in `/home/zliu/pvaPy/tools/local/pvapy-local/build/pvaPy-4.0.3':
configure: error: Could not verify boost python library; check your boost installation
See `config.log' for more details
Makefile:53: recipe for target 'configure' failed
make[2]: *** [configure] Error 1
make[2]: Leaving directory '/home/zliu/pvaPy/tools/local/pvapy-local/build/pvaPy-4.0.3'
Makefile:11: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/home/zliu/pvaPy/tools/local/pvapy-local'
Makefile:111: recipe for target 'package-pvapy-local' failed
make: *** [package-pvapy-local] Error 2

**Comment by sveseli** [comment]
Pip packages for arm64 (linux-aarch64) are available via pip now.
