### ISSUE TITLE
PvaServer.addRecord not working on Windows 10

### ISSUE THREAD

**Issue by joshikk** [epics-base/pvaPy#72]
I tried pvaccess server on Windows 10 I am unable to add a record to the server.
I tried it with pvapy 4.0.3 and 4.0.2 version.
My python installation is 3.9 on windows
The error is as below.

    server.addRecord(sd.ioc+sd.rscan_name+':block_table', blk_tablePV)
Boost.Python.ArgumentError: Python argument types in
    PvaServer.addRecord(PvaServer, str, PvObject)
did not match C++ signature:
    addRecord(class PvaServer {lvalue}, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > channelName, class PvObject pvObject, class boost::python::api::object onWriteCallback)

**Comment by sveseli** [comment]
Can you please try adding "None" as the third (callback) argument? I believe this is needed on windows.

**Comment by joshikk** [comment]
It is working thank you.
