### ISSUE TITLE
PyPI: pvaPy on Raspberry Pi

### ISSUE THREAD

**Issue by joshikk** [epics-base/pvaPy#73]
Hi,
I am unable to get pvaPy from the PyPI repository for my Raspberry Pi.
It would be great if wheel for the Raspberry/ARM  are available on PyPI.
Till then I may have to do a manual compile and install.

Thank you in advance
Kuldeep

**Comment by sveseli** [comment]
Just to clarify, you are looking for arm/v7 packages? I managed to get things going on arm64/v8, but not yet for arm/v7.

**Comment by joshikk** [comment]
I have embedded the 64 bit kernel on Pi 4B. I can give it a try, i.e. if it
has all the required 64 bit libraries included.

**Comment by sveseli** [comment]
Just like all pvapy pip packages, it contains all needed epics and boost libraries. Packages exist for python 3.6-3.10.

**Comment by joshikk** [comment]
Is it available online or is it under testing?

**Comment by sveseli** [comment]
should be available on pypi: https://pypi.org/project/pvapy/#files (e.g., https://files.pythonhosted.org/packages/f5/40/2f733dbcd5a8cc235c01d98d3d18b1e822f314a070d1f95fa48e36e4d44a/pvapy-4.1.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl)

**Comment by joshikk** [comment]
Hi,
I changed the PI 4 Kernel to 64 bit.
Linux raspberrypi 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020
aarch64 GNU/Linux

I am using the Python 3.7.3 version which is available with Raspberry OS
(32 bit) accordingly I selected the wheel
https://files.pythonhosted.org/packages/06/d1/535d51e75c1c044efe8de18d4500e3e15a8f6d9ea33fb136bffa618fb5fd/pvapy-4.1.0-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
I am getting a not supported wheel on this platform error.

Am I missing something, Do I have to get/compile Python for 64 bit arch??

**Comment by sveseli** [comment]
All libraries I've got at the moment are built for 64 bit, on a 64 bit python.

**Comment by joshikk** [comment]
Thank you. I guess I will upgrade my OS to bullseye. That should solve the
problem.

**Comment by sveseli** [comment]
Okay, let me know if it works once you upgrade.

**Comment by joshikk** [comment]
I could install the pypva wheel with the Raspbian 64 bit Bullseye, the
apt-repository is from debian.
Once I test it with EPICS and phoebus, I will update here.

**Comment by joshikk** [comment]
it should read as pvapy
