### ISSUE TITLE
add custom field to NTSCALAR record

### ISSUE THREAD

**Issue by basilaljamal** [epics-base/pvaPy#77]
I wondering if it is possible to add a custom field to an NTSCALAR record and still be considered an NTSCALAR record.
I need that for the EPICS archiver appliance because it would archive a PVACCESS record only if it is NTSCALAR, but in my case, I need to add custom fields.

**Comment by sveseli** [comment]
If you want to create NT Scalar, you can do something like this:

<pre>
>>> s = NtScalar(INT)
>>> s['value'] = 3
>>> print(s)
epics:nt/NTScalar:1.0 
    int value 3
    string descriptor 
    structure alarm
        int severity 0
        int status 0
        string message 
    structure timeStamp
        long secondsPastEpoch 0
        int nanoseconds 0
        int userTag 0
    structure display
        double limitLow 0
        double limitHigh 0
        string description 
        string format 
        string units 
    structure control
        double limitLow 0
        double limitHigh 0
        double minStep 0
</pre>

If you want to create record that looks like NT Scalar, but has extra fields, you can do something like this:

<pre>
>>> s2 = PvObject({'value' : INT, 'descriptor' : STRING, 'alarm' : PvAlarm(), 'timeStamp' : PvTimeStamp(), 'display' : PvDisplay(), 'control' : PvControl(), 'myCustomField' : DOUBLE}, 'epics:nt/NTScalar:1.0')
>>> s2['value'] = 3
>>> s2['myCustomField'] = 11.5
>>> print(s2)
epics:nt/NTScalar:1.0 
    int value 3
    string descriptor 
    alarm_t alarm
        int severity 0
        int status 0
        string message 
    time_t timeStamp
        long secondsPastEpoch 0
        int nanoseconds 0
        int userTag 0
    display_t display
        double limitLow 0
        double limitHigh 0
        string description 
        string format 
        string units 
    control_t control
        double limitLow 0
        double limitHigh 0
        double minStep 0
    double myCustomField 11.5
</pre>

Whether the above structure will be acceptable for the archiver appliance, I am not quite sure.
