### ISSUE TITLE
Can't install for Python 3.10 on Mac

### ISSUE THREAD

**Issue by wigging** [epics-base/pvaPy#86]
I'm on macOS version 12.7 and tried to install the package using `conda install -c epics pvapy` into a conda environment that uses Python 3.10. Unfortunately, I get the following error:

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pvapy -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.6,<3.7.0a0']

Your python: python=3.10

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

According to the files in the conda channel at https://anaconda.org/epics/pvapy/files, the Linux version of the package goes up to Python 3.11 but the Mac version stops at Python 3.9. Can you release a Mac version of the package that supports Python 3.10?

**Comment by sveseli** [comment]
Ahh, sorry, I will try to rectify this as soon as possible.

In the meantime, could you simply try "pip install pvapy"? This should work for now in your conda environment.

**Comment by wigging** [comment]
I would prefer to install with conda so it can resolve dependencies in the conda environment. If I use pip then I'll lose that benefit. Anyway, I'll wait on a fix and thank you for the quick response.

**Comment by sveseli** [comment]
Okay, I will try to restore OSX conda builds as soon as possible.

**Comment by wigging** [comment]
> In the meantime, could you simply try "pip install pvapy"? This should work for now in your conda environment.

@sveseli What Python versions does the pip package support on macOS (OSX)?

**Comment by sveseli** [comment]
3.8-3.11. They were built on OSX 10.15, so should work okay for you.

I started working on getting conda build machine back up. Sorry for the delay.

**Comment by sveseli** [comment]
Conda build for OSX was restored with 5.3.1 as the latest version. Packages were built on OSX 10.15, for python 3.8-3.11. Please give it a try, and let me know if there are any issues. I will leave the issue open for a few more days.

<pre>
$ curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 85.0M  100 85.0M    0     0  10.8M      0  0:00:07  0:00:07 --:--:-- 11.6M
$ sh Miniconda3-latest-MacOSX-x86_64.sh -b -p CONDA
PREFIX=/Users/sveseli/PVAPY/CONDA
...
installation finished.
$ source CONDA/etc/profile.d/conda.sh              
$ conda activate                                   
$ conda install -c epics pvapy
Retrieving notices: ...working... done
...
Executing transaction: done                                                     $

$ conda list pvapy
# packages in environment at /Users/sveseli/PVAPY/CONDA:
#
# Name                    Version                   Build  Channel
pvapy                     5.3.1                   py311_1    epics
pvapy-boost               1.81.0                  py311_1    epics
$  python -c "from pvapy import *; pv = PvInt(3); print(pv)"
3

</pre>

**Comment by wigging** [comment]
I can verify that this works now. I installed the package on macOS using conda in a Python 3.10 environment without any issues. Thank you for the quick fix. You can close this issue.
