### ISSUE TITLE
Unable to install on Macs that use Apple M-series (ARM) chips

### ISSUE THREAD

**Issue by wigging** [epics-base/pvaPy#87]
Installing the pvapy package on an Apple MacBook Pro (M series, ARM) fails in a conda environment as shown below:

```
Channels:
 - defaults
 - epics
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed
PackagesNotFoundError: The following packages are not available from current channels:
  - pvapy
Current channels:
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://conda.anaconda.org/epics/osx-arm64
To search for alternate channels that may provide the conda package you're
looking for, navigate to
    https://anaconda.org/
and use the search bar at the top of the page.
```

The same problem occurs when trying to install in a Python virtual environment using pip. It looks like the pvapy package is not installable on Macs that use the Apple M-series chips which are ARM processors.

**Comment by SeijDeLeon** [comment]
I was able to install pvapy on a 2020 Apple M1 (Ventura 13.4.1) using pip. 

I am unable to install pvapy on a 2023 Apple M2 (Sonoma 14.0) using either pip or conda.  Not sure why it worked on the M1 but not the M2.

**Comment by sveseli** [comment]
Sorry for the delay in response. I do not really have access to M2 machine for builds/packaging yet, but should get this in the next few weeks, at which point I'll try to generate package that you could use.

**Comment by sveseli** [comment]
Could you please try "pip install pvapy" on your M2 machine, and let me know if it works?

I see this in my environment:

<pre>
$ uname -a
Darwin ... 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112 arm64

$ pip install pvapy
Collecting pvapy
  Downloading pvapy-5.4.0-cp312-cp312-macosx_14_0_arm64.whl.metadata (14 kB)
Collecting numpy>=1.26 (from pvapy)
  Using cached numpy-1.26.4-cp312-cp312-macosx_11_0_arm64.whl.metadata (61 kB)
Downloading pvapy-5.4.0-cp312-cp312-macosx_14_0_arm64.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 4.9 MB/s eta 0:00:00
Using cached numpy-1.26.4-cp312-cp312-macosx_11_0_arm64.whl (13.7 MB)
Installing collected packages: numpy, pvapy
Successfully installed numpy-1.26.4 pvapy-5.4.0
</pre>

**Comment by SeijDeLeon** [comment]
Just tried on an M2, looks like it worked!

```
pip install pvapy
Collecting pvapy
  Downloading pvapy-5.4.0-cp311-cp311-macosx_14_0_arm64.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.22 in ./miniconda3/lib/python3.11/site-packages (from pvapy) (1.24.2)
Downloading pvapy-5.4.0-cp311-cp311-macosx_14_0_arm64.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 44.9 MB/s eta 0:00:00
Installing collected packages: pvapy
Successfully installed pvapy-5.4.0
```

**Comment by sveseli** [comment]
Sounds good, thanks for letting me know. I'll close this issue, and if you see any problems with OSX/Arm64 package, let me know or open a new issue.
